##############################
########## Parkings ##########
##############################

########## GET ##########

GET https://localhost:44360/api/Parkings
# apikey: exampleKey1234
apikey: apikey1234_admin

###

GET https://localhost:44360/api/Parkings/1
apikey: apikey1234_visitor
# apikey: apikey1234_admin

###

GET https://localhost:44360/api/Parkings/Active
Content-Type: application/json
apikey: apikey1234_visitor

###

GET https://localhost:44360/api/Parkings/Active?traveller=Luke
Content-Type: application/json
apikey: apikey1234_visitor
# apikey: apikey1234_admin

###

GET https://localhost:44360/api/Parkings/Ended?traveller=Han Solo
Content-Type: application/json
apikey: apikey1234_visitor
# apikey: apikey1234_admin

###

POST https://localhost:44360/api/Parkings
Content-Type: application/json
apikey: apikey1234_visitor
# apikey: apikey1234_admin

{
    "Traveller":"Han Solo",
    "Starship":"Millennium Falcon",
    "SpaceportId":1
}

###

PUT https://localhost:44360/api/Parkings/Checkout/4
Content-Type: application/json
apikey: apikey1234_visitor
# apikey: apikey1234_admin

{
}

###

PATCH https://localhost:44360/api/Parkings/Checkout?traveller=Not Luke again 2
Content-Type: application/json
apikey: apikey1234_visitor
# apikey: apikey1234_admin

{
}

################################
########## Spaceports ##########
################################

########## GET ##########

GET https://localhost:44360/api/Spaceports
apikey: apikey1234_visitor
# apikey: apikey1234_admin

###

GET https://localhost:44360/api/Spaceports/4
apikey: apikey1234_visitor

########## POST ##########

POST https://localhost:44360/api/Spaceports
Content-Type: application/json
# apikey: apikey1234_visitor
apikey: apikey1234_admin

{
    "Name":"Mos Eisley"
}

########## PUT ##########

PUT https://localhost:44360/api/Spaceports/2
Content-Type: application/json

{
    "Id":2,
    "PlanetName":"Naboo",
    "Name":"NabooPort"
}

############################
########## People ##########
############################

########## GET ##########

GET https://localhost:44360/api/People
apikey: apikey1234_visitor

###

GET https://localhost:44360/api/People/All
apikey: apikey1234_visitor

###

GET https://localhost:44360/api/People?name=Luke Skywalker
apikey: apikey1234_visitor

###############################
########## Starships ##########
###############################

########## GET ##########

GET https://localhost:44360/api/Starships/All
apikey: apikey1234_visitor

###

GET https://localhost:44360/api/starships?name=Millennium Falcon
apikey: apikey1234_visitor
