##############################
########## Parkings ##########
##############################

########## GET ##########

GET https://localhost:44360/api/Parkings

###

POST https://localhost:44360/api/Parkings
Content-Type: application/json
apikey: secret1234

{
    "Traveller":"Luke5",
    "StarShip":"X-Wing5",
    "SpaceportId":1
}

###

POST https://localhost:44360/api/Parkings
Content-Type: application/json

{
    "Traveller":"Luke",
    "StarShip":"X-Wing",
    "Spaceport":
    {
        "planetName": "Tatooine",
        "name": "TatooinePort"
    }
}

###

DELETE https://localhost:44360/api/Parkings/1

################################
########## Spaceports ##########
################################

########## GET ##########

GET https://localhost:44360/api/Spaceports
apikey: apikey1234_visitor
# apikey: apikey1234_admin

###

GET https://localhost:44360/api/Spaceports/1
apikey: secret1234

########## POST ##########

POST https://localhost:44360/api/Spaceports
Content-Type: application/json
# apikey: secret1234
# apikey: apikey1234_visitor
apikey: apikey1234_admin

{
    "PlanetName":"Tatooine50055",
    "Name":"TatooinePort50055"
}

########## PUT ##########

PUT https://localhost:44360/api/Spaceports/2
Content-Type: application/json

{
    "Id":2,
    "PlanetName":"Naboo",
    "Name":"NabooPort"
}

############################
########## People ##########
############################

########## GET ##########

GET https://localhost:44360/api/People
apikey: apikey1234_visitor

###

GET https://localhost:44360/api/People
apikey: secret1234

###############################
########## Starships ##########
###############################

########## GET ##########

GET https://localhost:44360/api/Starships
apikey: secret1234

###

GET https://localhost:44360/api/Starships/3
apikey: secret1234
